name: Main Taski Workflow

on:
  push:
    branches:
      - main
jobs:
  checkout-and-print-trees:
    runs-on: ubuntu_latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print project tree
        uses: tree .
